apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: go-demo-3-build
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--context=git://github.com/baydakovss/go-demo-3",
            "--destination=baydakovss/go-demo-3:1.0.0"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json

